#this run on every {issues}
name: Time&&Ip

# on: issues

on:
  issues:
    types: opened

jobs:
  time-of-vm:
    runs-on: ubuntu-latest
    steps:
      - name: time
        run: echo "today date and ip address $(date) $(hostname -I)"
#types: [opened, edited, milestoned]
#types: [created, deleted]
##types: [opened, deleted] this only run on certian condtions
