# name: Testing corn jobs

# on:
#   schedule:
#     - cron: "*/1 * * * *"

# jobs:
#   show-time:
#     runs-on: ubuntu-latest
#     steps:
#       - name: print time
#         run: echo "today date and ip address $(date) $(hostname -I)"

name: Testing cron jobs

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  show-time:
    runs-on: ubuntu-latest
    steps:
      - name: Print date and IP address
        run: echo "Today's date $(date)"
