name: Testing corn jobs

on:
  schedule:
    - cron: "*/3 * * * *"

jobs:
  show-time:
    runs-on: ubuntu-latest
    steps:
      - name: print time
        run: echo "today date and ip address ${date} ${hostname -I}"
