name: Testing corn jobs
on:
  schedule:
    - cron: "*/1 * * * *" ## only runs every 5min even it should run every 1min

jobs:
  show-time:
    runs-on: ubuntu-latest
    steps:
      - name: print time
        run: echo "today date and ip address $(date) $(hostname -I)"
